# Generated by Django 4.2.5 on 2023-10-05 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("album", models.CharField(max_length=200)),
                ("artists", models.CharField(max_length=300)),
                ("genre", models.CharField(max_length=400)),
                (
                    "author_tags",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("bezradność", "bezradność"),
                            ("błogo", "błogo"),
                            ("ciekawe", "ciekawe"),
                            ("duma", "duma"),
                            ("fantastycznie", "fantastycznie"),
                            ("gniew", "gniew"),
                            ("głupio", "głupio"),
                            ("imprezowo", "imprezowo"),
                            ("intrygujące", "intrygujące"),
                            ("irytacja", "irytacja"),
                            ("koncentracja", "koncentracja"),
                            ("miłość", "miłość"),
                            ("motywacja", "motywacja"),
                            ("młodość", "młodość"),
                            ("nadzieja", "nadzieja"),
                            ("natchnienie", "natchnienie"),
                            ("nostalgia", "nostalgia"),
                            ("obojętność", "obojętność"),
                            ("pięknie", "pięknie"),
                            ("podekscytowanie", "podekscytowanie"),
                            ("poważnie", "poważnie"),
                            ("przygnębienie", "przygnębienie"),
                            ("przygoda", "przygoda"),
                            ("radość", "radość"),
                            ("relaks", "relaks"),
                            ("rodzinnie", "rodzinnie"),
                            ("samotność", "samotność"),
                            ("senność", "senność"),
                            ("sentymentalnie", "sentymentalnie"),
                            ("smutek", "smutek"),
                            ("spokój", "spokój"),
                            ("starość", "starość"),
                            ("strach", "strach"),
                            ("szaleństwo", "szaleństwo"),
                            ("szczęście", "szczęście"),
                            ("słodko", "słodko"),
                            ("tęsknota", "tęsknota"),
                            ("wakacyjnie", "wakacyjnie"),
                            ("wdzięczność", "wdzięczność"),
                            ("wolność", "wolność"),
                            ("wspaniale", "wspaniale"),
                            ("wzruszenie", "wzruszenie"),
                            ("zakochanie", "zakochanie"),
                            ("zazdrość", "zazdrość"),
                            ("zdziwienie", "zdziwienie"),
                            ("zmartwienie", "zmartwienie"),
                            ("zmęczenie", "zmęczenie"),
                            ("znudzenie", "znudzenie"),
                            ("złamane serce", "złamane serce"),
                            ("złość", "złość"),
                            ("świątecznie", "świątecznie"),
                        ],
                        max_length=51,
                    ),
                ),
                ("image", models.URLField()),
                ("audio", models.URLField(blank=True, null=True)),
                ("slug", models.SlugField(blank=True, max_length=200)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "friend_tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tagged_in",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "users_like",
                    models.ManyToManyField(
                        blank=True,
                        related_name="posts_liked",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "post",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="posts.post",
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
    ]
