# Generated by Django 4.2.5 on 2023-09-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="artist",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="post",
            name="genre",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
