# Generated by Django 4.2.5 on 2023-09-19 22:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0002_post_artist_post_genre"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="tags",
            new_name="author_tags",
        ),
        migrations.RemoveField(
            model_name="post",
            name="url",
        ),
        migrations.AddField(
            model_name="post",
            name="album",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="post",
            name="friend_tags",
            field=models.ManyToManyField(
                blank=True, related_name="tagged_users", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="artist",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="post",
            name="genre",
            field=models.CharField(max_length=200),
        ),
    ]
