# Generated by Django 4.2.5 on 2023-09-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_rename_tags_post_author_tags_remove_post_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="album",
            field=models.CharField(max_length=200),
        ),
    ]
