# Generated by Django 4.2.5 on 2023-09-20 00:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_alter_post_album"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, upload_to="posts_photos/%Y/%m/%d"),
        ),
    ]
