# Generated by Django 4.2.5 on 2023-09-27 21:08

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0006_alter_post_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="author_tags",
        ),
        migrations.AddField(
            model_name="post",
            name="author_tags",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("bezradność", "bezradność"),
                    ("błogo", "błogo"),
                    ("ciekawe", "ciekawe"),
                    ("duma", "duma"),
                    ("fantastycznie", "fantastycznie"),
                    ("gniew", "gniew"),
                    ("głupio", "głupio"),
                    ("imprezowo", "imprezowo"),
                    ("intrygujące", "intrygujące"),
                    ("irytacja", "irytacja"),
                    ("koncentracja", "koncentracja"),
                    ("miłość", "miłość"),
                    ("motywacja", "motywacja"),
                    ("młodość", "młodość"),
                    ("nadzieja", "nadzieja"),
                    ("natchnienie", "natchnienie"),
                    ("nostalgia", "nostalgia"),
                    ("obojętność", "obojętność"),
                    ("pięknie", "pięknie"),
                    ("podekscytowanie", "podekscytowanie"),
                    ("poważnie", "poważnie"),
                    ("przygnębienie", "przygnębienie"),
                    ("przygoda", "przygoda"),
                    ("radość", "radość"),
                    ("relaks", "relaks"),
                    ("rodzinnie", "rodzinnie"),
                    ("samotność", "samotność"),
                    ("senność", "senność"),
                    ("sentymentalnie", "sentymentalnie"),
                    ("smutek", "smutek"),
                    ("spokój", "spokój"),
                    ("starość", "starość"),
                    ("strach", "strach"),
                    ("szaleństwo", "szaleństwo"),
                    ("szczęście", "szczęście"),
                    ("słodko", "słodko"),
                    ("tęsknota", "tęsknota"),
                    ("wakacyjnie", "wakacyjnie"),
                    ("wdzięczność", "wdzięczność"),
                    ("wolność", "wolność"),
                    ("wspaniale", "wspaniale"),
                    ("wzruszenie", "wzruszenie"),
                    ("zakochanie", "zakochanie"),
                    ("zazdrość", "zazdrość"),
                    ("zdziwienie", "zdziwienie"),
                    ("zmartwienie", "zmartwienie"),
                    ("zmęczenie", "zmęczenie"),
                    ("znudzenie", "znudzenie"),
                    ("złamane serce", "złamane serce"),
                    ("złość", "złość"),
                    ("świątecznie", "świątecznie"),
                ],
                max_length=51,
            ),
        ),
    ]
