# Generated by Django 4.2.5 on 2023-09-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0007_remove_post_author_tags_post_author_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.URLField(),
        ),
    ]
