# Generated by Django 4.2.5 on 2023-09-28 10:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0008_alter_post_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="artist",
            new_name="artists",
        ),
    ]
