# Generated by Django 4.2.5 on 2023-09-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0009_rename_artist_post_artists"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="audio",
            field=models.URLField(blank=True),
        ),
    ]
