# Generated by Django 4.2.5 on 2023-09-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0011_post_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
