# Generated by Django 4.2.5 on 2023-09-28 12:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0015_alter_post_artists_alter_post_genre"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created"]},
        ),
    ]
