# Generated by Django 4.2.5 on 2023-09-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0016_alter_post_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
