# Generated by Django 4.2.5 on 2023-09-28 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0017_alter_post_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="friend_tags",
            field=models.ManyToManyField(
                blank=True, related_name="tagged_in", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
