# Generated by Django 4.2.5 on 2023-09-28 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0019_alter_post_audio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="username",
        ),
        migrations.AddField(
            model_name="comment",
            name="username",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
