# Generated by Django 4.2.5 on 2023-10-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="private_mode",
            field=models.BooleanField(default=False),
        ),
    ]
