# Generated by Django 4.2.5 on 2023-09-28 22:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_remove_profile_profile_photo_profile_photo_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ["-created"]},
        ),
    ]
