# Generated by Django 4.2.5 on 2023-09-28 22:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_alter_contact_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={},
        ),
    ]
