tag_moods = sorted(['szczęście',
                    'smutek',
                    'wdzięczność',
                    'podekscytowanie',
                    'zakochanie',
                    'szaleństwo',
                    'głupio',
                    'świątecznie',
                    'wakacyjnie',
                    'imprezowo',
                    'błogo',
                    'relaks',
                    'zmęczenie',
                    'motywacja',
                    'duma',
                    'samotność',
                    'nostalgia',
                    'sentymentalnie',
                    'znudzenie',
                    'spokój',
                    'słodko',
                    'wspaniale',
                    'fantastycznie',
                    'zmartwienie',
                    'natchnienie',
                    'przygnębienie',
                    'intrygujące',
                    'ciekawe',
                    'złość',
                    'gniew',
                    'zdziwienie',
                    'obojętność',
                    'pięknie',
                    'wolność',
                    'starość',
                    'młodość',
                    'strach',
                    'zazdrość',
                    'nadzieja',
                    'wzruszenie',
                    'irytacja',
                    'złamane serce',
                    'tęsknota',
                    'bezradność',
                    'poważnie',
                    'koncentracja',
                    'senność',
                    'przygoda',
                    'rodzinnie',
                    'miłość',
                    'radość'])


tag_moods_as_choices = tuple([(mood, mood) for mood in tag_moods])

    